### ISSUE TITLE
Newsletter sign up bug

### ISSUE THREAD

**Issue by lukefretwell** [FDA/open.fda.gov#69] opened 2014-09-06 21:57 UTC
Got this message/error when trying to sign up for the openFDA newsletter:

"We ran into a technical problem signing you up from this page. Please sign up at the NIH web site."

Screenshot:

![screen shot 2014-09-06 at 2 55 13 pm](https://cloud.githubusercontent.com/assets/1569463/4176715/b7d58dae-3610-11e4-8e95-db2d89d5671c.png)

**Comment by afeld** [comment] 2018-09-18 04:39
Duplicate of #54.

**Closed** 2019-10-04 18:30 UTC
